name = "shahed-aqarak"
type = "javascript"

[build]
command = "yarn install --frozen-lockfile=false && yarn build"
cwd = "."
watch_paths = ["src/**/*.jsx"]

[build.upload]
format = "service-worker"

[env.production]
route = "shahed-aqarak.pages.dev"
zone_id = ""
